apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: cinemaabyss
  labels:
    app: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: ghcr.io/mafesenko/architecture-sprint-2/events-service:sha-e152273@sha256:81053a2e033a4b6262dcc4bcc87d99d8c6965dd6af2c7189564beadd5da824d2
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: KAFKA_BROKER
          value: "kafka:9092"
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        readinessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 20  # Ждем Kafka
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 40
          periodSeconds: 10
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: cinemaabyss
spec:
  selector:
    app: events-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP